version: '3.8'

services:
  sheetful-api:
    build: .
    ports:
      - "3001:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PORT=8000
    volumes:
      - .:/app
    restart: unless-stopped
